In [1]:
import pandas as pd
import numpy as np

In [2]:
# ---GET TO KNOW THE DATA--- (Step 1 And Step 2)
df = pd.read_csv('dirty_synthetic_ecommerce_tr_1700.csv')

print("---Data Info Here---")
df.info()

print("\n---First 5 Rows---")
display(df.head(5))

print("\n---Last 5 Rows---")
display(df.tail())

---Data Info Here---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1725 entries, 0 to 1724
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Year                 1712 non-null   float64
 1   OrderID              1708 non-null   object
 2   GENDER               1710 non-null   object
 3   Age                  1708 non-null   float64
 4    City                1707 non-null   object
 5   membershipTier       1703 non-null   object
 6   Device_type          1710 non-null   object
 7   traffic Source       1705 non-null   object
 8   payment_method       1707 non-null   object
 9   ProductCategory      1706 non-null   object
 10  Items_in_cart        1707 non-null   float64
 11  BasketValueTRY       1713 non-null   float64
 12  Discount Rate        1708 non-null   object
 13  delivery_days        1714 non-null   float64
 14  SatisfactionScore    1713 non-null   float64
 15  Repeat_Purchase_90D  1699 non-null   float64
dtypes: float64(7), object(9)
memory usage: 215.8+ KB

---First 5 Rows---

,Year,OrderID,GENDER,Age,City,membershipTier,Device_type,traffic Source,payment_method,ProductCategory,Items_in_cart,BasketValueTRY,Discount Rate,delivery_days,SatisfactionScore,Repeat_Purchase_90D
0,2019.0,ORD2019000001,MALE,42.0,KAYSERI,bronze,desktop,Organic,Cr3dit Card,FASHION,5.0,345.30,0.116%,2.0,3.6,1.0
1,2024.0,ORD2024000002,Male,32.0,Bursa,bronze,MOBILE,social,Cr3dit Card,Electronics*,1.0,275.39,0.104%,2.0,4.3,1.0
2,2023.0,ORD2023000003,F3mal3,27.0,i̇stanbul,BRONZE,MOBILE,social,Credit Card,Fashion,3.0,797.88,0.258%,2.0,5.0,1.0
3,2018.0,ORD2018000004,MALE,44.0,Adana,gold,desktop,organic,DEBIT CARD,Groceries,4.0,275.08,0.13%,2.0,4.2,1.0
4,2018.0,ORD2018000005,Male,18.0,Antalya,Bronze,Mobil3,email,Cr3dit Card,SPORTS,2.0,910.98,0.156%,3.0,3.3,0.0

---Last 5 Rows---

,Year,OrderID,GENDER,Age,City,membershipTier,Device_type,traffic Source,payment_method,ProductCategory,Items_in_cart,BasketValueTRY,Discount Rate,delivery_days,SatisfactionScore,Repeat_Purchase_90D
1720,2019.0,ORD2019001359,Female,23.0,İstanbul,Silver,Mobile,Social,Credit Card,Fashion,1.0,169.62,0.14%,1.0,4.0,0.0
1721,2023.0,ORD2023000024,Female,44.0,Ankara,Bronze,Mobile,Organic,Credit Card,Beauty,3.0,419.58,0.188%,3.0,3.7,0.0
1722,2022.0,ORD2022000716,Female,35.0,Bursa,Silver,Mobile,Organic,Credit Card,Fashion,4.0,683.13,0.089%,3.0,4.7,0.0
1723,2022.0,ORD2022000079,Male,26.0,İstanbul,Bronze,Mobile,Paid Search,Credit Card,Fashion,3.0,291.75,0.216%,2.0,4.1,0.0
1724,2020.0,ORD2020001281,Female,42.0,İstanbul,Silver,Mobile,Social,Credit Card,Home & Kitchen,1.0,138.94,0.258%,1.0,3.8,0.0

In [3]:
# ---IF THIS DATA TIDY?--- (STEP 3)

#To check we have actual column names (variable names).
print("Current Column Names:")
print(list(df.columns))

#to see the structre of first 3 rows
display(df.head(3))

Current Column Names:
['Year', 'OrderID ', 'GENDER', 'Age', ' City', 'membershipTier', 'Device_type', 'traffic Source', 'payment_method ', 'ProductCategory', 'Items_in_cart', 'BasketValueTRY', 'Discount Rate', 'delivery_days ', 'SatisfactionScore', 'Repeat_Purchase_90D']

,Year,OrderID,GENDER,Age,City,membershipTier,Device_type,traffic Source,payment_method,ProductCategory,Items_in_cart,BasketValueTRY,Discount Rate,delivery_days,SatisfactionScore,Repeat_Purchase_90D
0,2019.0,ORD2019000001,MALE,42.0,KAYSERI,bronze,desktop,Organic,Cr3dit Card,FASHION,5.0,345.30,0.116%,2.0,3.6,1.0
1,2024.0,ORD2024000002,Male,32.0,Bursa,bronze,MOBILE,social,Cr3dit Card,Electronics*,1.0,275.39,0.104%,2.0,4.3,1.0
2,2023.0,ORD2023000003,F3mal3,27.0,i̇stanbul,BRONZE,MOBILE,social,Credit Card,Fashion,3.0,797.88,0.258%,2.0,5.0,1.0

In [4]:
# --- FIXING COLUMN NAMES --- (Step 4)

#first we see the original column names in order to check whether we did our job well or not at the end.
print("Original Column Names:")
print(list(df.columns))

#removing whitespaces here
df.columns = df.columns.str.strip()

#standardizing all variable names here
df.columns = df.columns.str.lower()

#replacing any spaces with underscores here
df.columns = df.columns.str.replace(" ", "_")

df = df.rename(columns={
    "membershiptier": "membership_tier",
    "basketvaluetry": "basket_value_try",
    "productcategory": "product_category",
    "satisfactionscore": "satisfaction_score",
    })

#the result must be shown here
print("\nCorrected And Fixed Column Names: ")
print(list(df.columns))

Original Column Names:
['Year', 'OrderID ', 'GENDER', 'Age', ' City', 'membershipTier', 'Device_type', 'traffic Source', 'payment_method ', 'ProductCategory', 'Items_in_cart', 'BasketValueTRY', 'Discount Rate', 'delivery_days ', 'SatisfactionScore', 'Repeat_Purchase_90D']

Corrected And Fixed Column Names:
['year', 'orderid', 'gender', 'age', 'city', 'membership_tier', 'device_type', 'traffic_source', 'payment_method', 'product_category', 'items_in_cart', 'basket_value_try', 'discount_rate', 'delivery_days', 'satisfaction_score', 'repeat_purchase_90d']

In [ ]:
# ---REMOVING UNNECESSARY COLUMNS--- (Step 5)

#as we will not take orderid column into consideration (mostly) we can drop it.
df = df.drop(columns= ["orderid"], errors="ignore") #to prevent any erros in jupiter notebook

print("\nCurrent Columns: ")
print(list(df.columns))

Current Columns:
['year', 'gender', 'age', 'city', 'membership_tier', 'device_type', 'traffic_source', 'payment_method', 'product_category', 'items_in_cart', 'basket_value_try', 'discount_rate', 'delivery_days', 'satisfaction_score', 'repeat_purchase_90d']

In [6]:
# --- REMOVING DUPLICATES ---  (Step 6)

#we can verify at the end if we count our duplicated results first. also we need to check whether we have duplicates or not.
nDuplicates = df.duplicated().sum()
print(f"Number of duplicates: {nDuplicates}")

#we do not have duplicates yet; however, we did not standardize our table.
df = df.drop_duplicates()

#verifying the result here
print(f"All duplicates are deleted. New row count: {len(df)}")

Number of duplicates: 0
All duplicates are deleted. New row count: 1725

In [ ]:
# --- REMOVING  UNNECESSARY CHARACTERS IN VALUES --- (Step 7)

# we will go by column by column. we can check if there are any unnecessary strings. then remove or replace them.
display(df.head(15)) # to see our data and detect the unnecesary characters.

# we do not need '%' sign here, so we remove it.
df['discount_rate'] = df['discount_rate'].astype(str).str.replace('%', '', regex=False) #regex is false here because we do not look for repeated values

# there are many * signs in our data. we can remove them bu using loops.
text_columns = df.select_dtypes(include=['object']).columns
for col in text_columns:
    if df[col].astype(str).str.contains('*', regex=False).any(): #any column that contains * sign in them
        print(f"Cleaning '*' from column: {col}") # to see which colum had * sign
        df[col] = df[col].astype(str).str.replace('*', '', regex=False)

display(df.head(15))

,year,gender,age,city,membership_tier,device_type,traffic_source,payment_method,product_category,items_in_cart,basket_value_try,discount_rate,delivery_days,satisfaction_score,repeat_purchase_90d
0,2019.0,MALE,42.0,KAYSERI,bronze,desktop,Organic,Cr3dit Card,FASHION,5.0,345.30,0.116%,2.0,3.6,1.0
1,2024.0,Male,32.0,Bursa,bronze,MOBILE,social,Cr3dit Card,Electronics*,1.0,275.39,0.104%,2.0,4.3,1.0
2,2023.0,F3mal3,27.0,i̇stanbul,BRONZE,MOBILE,social,Credit Card,Fashion,3.0,797.88,0.258%,2.0,5.0,1.0
3,2018.0,MALE,44.0,Adana,gold,desktop,organic,DEBIT CARD,Groceries,4.0,275.08,0.13%,2.0,4.2,1.0
4,2018.0,Male,18.0,Antalya,Bronze,Mobil3,email,Cr3dit Card,SPORTS,2.0,910.98,0.156%,3.0,3.3,0.0
5,2021.0,male,18.0,ankara,Silver,Mobil3,email,Digital Wallet,HOME & KITCHEN,3.0,NaN,0.309%,3.0,3.2,0.0
6,2024.0,Male,40.0,İSTANBUL,Silv3r,MOBILE,Organic,cash on delivery,HOME & KITCHEN,1.0,640.46,0.137%,1.0,4.8,1.0
7,2020.0,female,27.0,Ankara*,Silver,tablet,Paid S3arch,credit card,FASHION,3.0,1474.01,0.194%,4.0,3.9,1.0
8,2020.0,male,43.0,Trabzon,NaN,MOBILE,PAID SEARCH,Credit Card,Home & Kitchen*,2.0,496.99,0.211%,4.0,4.2,0.0
9,2023.0,male,42.0,Ankara,SILVER,Mobil3,organic,Bank Transfer,Books & Station3ry,4.0,269.77,0.165%,3.0,3.7,0.0
10,2018.0,MALE,44.0,ADANA,Silv3r,Mobile*,Email,Digital Wallet,ELECTRONICS,1.0,662.96,0.198%,3.0,3.2,0.0
11,2024.0,Female*,NaN,i̇stanbul,GUEST,desktop,EMAIL,Credit Card,fashion,3.0,362.91,0.072%,3.0,3.5,1.0
12,2024.0,male,29.0,Ankara*,SILVER,Mobile,email,Credit Card*,HOME & KITCHEN,2.0,1031.39,0.12%,3.0,4.4,1.0
13,2023.0,male,30.0,Mersin,Guest*,DESKTOP,email,Cr3dit Card,home & kitchen,1.0,195.65,0.16%,3.0,3.0,0.0
14,2024.0,male,35.0,ankara,Silv3r,Mobil3,Organic,Digital Wallet,Fashion,5.0,2929.20,0.008%,1.0,4.4,1.0

Cleaning '*' from column: gender
Cleaning '*' from column: city
Cleaning '*' from column: membership_tier
Cleaning '*' from column: device_type
Cleaning '*' from column: traffic_source
Cleaning '*' from column: payment_method
Cleaning '*' from column: product_category

,year,gender,age,city,membership_tier,device_type,traffic_source,payment_method,product_category,items_in_cart,basket_value_try,discount_rate,delivery_days,satisfaction_score,repeat_purchase_90d
0,2019.0,MALE,42.0,KAYSERI,bronze,desktop,Organic,Cr3dit Card,FASHION,5.0,345.30,0.116,2.0,3.6,1.0
1,2024.0,Male,32.0,Bursa,bronze,MOBILE,social,Cr3dit Card,Electronics,1.0,275.39,0.104,2.0,4.3,1.0
2,2023.0,F3mal3,27.0,i̇stanbul,BRONZE,MOBILE,social,Credit Card,Fashion,3.0,797.88,0.258,2.0,5.0,1.0
3,2018.0,MALE,44.0,Adana,gold,desktop,organic,DEBIT CARD,Groceries,4.0,275.08,0.13,2.0,4.2,1.0
4,2018.0,Male,18.0,Antalya,Bronze,Mobil3,email,Cr3dit Card,SPORTS,2.0,910.98,0.156,3.0,3.3,0.0
5,2021.0,male,18.0,ankara,Silver,Mobil3,email,Digital Wallet,HOME & KITCHEN,3.0,NaN,0.309,3.0,3.2,0.0
6,2024.0,Male,40.0,İSTANBUL,Silv3r,MOBILE,Organic,cash on delivery,HOME & KITCHEN,1.0,640.46,0.137,1.0,4.8,1.0
7,2020.0,female,27.0,Ankara,Silver,tablet,Paid S3arch,credit card,FASHION,3.0,1474.01,0.194,4.0,3.9,1.0
8,2020.0,male,43.0,Trabzon,nan,MOBILE,PAID SEARCH,Credit Card,Home & Kitchen,2.0,496.99,0.211,4.0,4.2,0.0
9,2023.0,male,42.0,Ankara,SILVER,Mobil3,organic,Bank Transfer,Books & Station3ry,4.0,269.77,0.165,3.0,3.7,0.0
10,2018.0,MALE,44.0,ADANA,Silv3r,Mobile,Email,Digital Wallet,ELECTRONICS,1.0,662.96,0.198,3.0,3.2,0.0
11,2024.0,Female,NaN,i̇stanbul,GUEST,desktop,EMAIL,Credit Card,fashion,3.0,362.91,0.072,3.0,3.5,1.0
12,2024.0,male,29.0,Ankara,SILVER,Mobile,email,Credit Card,HOME & KITCHEN,2.0,1031.39,0.12,3.0,4.4,1.0
13,2023.0,male,30.0,Mersin,Guest,DESKTOP,email,Cr3dit Card,home & kitchen,1.0,195.65,0.16,3.0,3.0,0.0
14,2024.0,male,35.0,ankara,Silv3r,Mobil3,Organic,Digital Wallet,Fashion,5.0,2929.20,0.008,1.0,4.4,1.0

In [8]:
# --- REMOVING WHITE SPACES --- (Step 8)

#selecting all string columns
space_columns = df.select_dtypes(include=["object"]).columns

#to see our data first
display(df[space_columns].head(5))

#using loop to remove all white spaces
for col in space_columns:
    df[col] = df[col].str.strip()

print("All white spaces are removed.")

#to verify our result
display(df[space_columns].head(5))

,gender,city,membership_tier,device_type,traffic_source,payment_method,product_category,discount_rate
0,MALE,KAYSERI,bronze,desktop,Organic,Cr3dit Card,FASHION,0.116
1,Male,Bursa,bronze,MOBILE,social,Cr3dit Card,Electronics,0.104
2,F3mal3,i̇stanbul,BRONZE,MOBILE,social,Credit Card,Fashion,0.258
3,MALE,Adana,gold,desktop,organic,DEBIT CARD,Groceries,0.13
4,Male,Antalya,Bronze,Mobil3,email,Cr3dit Card,SPORTS,0.156

All white spaces are removed.

,gender,city,membership_tier,device_type,traffic_source,payment_method,product_category,discount_rate
0,MALE,KAYSERI,bronze,desktop,Organic,Cr3dit Card,FASHION,0.116
1,Male,Bursa,bronze,MOBILE,social,Cr3dit Card,Electronics,0.104
2,F3mal3,i̇stanbul,BRONZE,MOBILE,social,Credit Card,Fashion,0.258
3,MALE,Adana,gold,desktop,organic,DEBIT CARD,Groceries,0.13
4,Male,Antalya,Bronze,Mobil3,email,Cr3dit Card,SPORTS,0.156

In [9]:
# --- CONVERTING ALL TEXTS TO LOWERCASE --- (Step 9)

#selecting our string columns
nuCols = df.select_dtypes(include=["object"]).columns

#see our data first
display(df[nuCols].head(5))

#using for loop to change them
for col in nuCols:
    df[col] = df[col].str.lower()

#verifying the result
display(df[nuCols].head(5))

,gender,city,membership_tier,device_type,traffic_source,payment_method,product_category,discount_rate
0,MALE,KAYSERI,bronze,desktop,Organic,Cr3dit Card,FASHION,0.116
1,Male,Bursa,bronze,MOBILE,social,Cr3dit Card,Electronics,0.104
2,F3mal3,i̇stanbul,BRONZE,MOBILE,social,Credit Card,Fashion,0.258
3,MALE,Adana,gold,desktop,organic,DEBIT CARD,Groceries,0.13
4,Male,Antalya,Bronze,Mobil3,email,Cr3dit Card,SPORTS,0.156

,gender,city,membership_tier,device_type,traffic_source,payment_method,product_category,discount_rate
0,male,kayseri,bronze,desktop,organic,cr3dit card,fashion,0.116
1,male,bursa,bronze,mobile,social,cr3dit card,electronics,0.104
2,f3mal3,i̇stanbul,bronze,mobile,social,credit card,fashion,0.258
3,male,adana,gold,desktop,organic,debit card,groceries,0.13
4,male,antalya,bronze,mobil3,email,cr3dit card,sports,0.156

In [10]:
# --- FIXING THE TYPOS --- (Step 10)

#defining all the values on our string columns and using loop to determine uniqueness
defCols = df.select_dtypes(include=["object"]).columns.drop('discount_rate')
for col in defCols:
    print(f"\n--- {col} ---")
    print(df[col].unique())

#we set a dictionary and replace the values
typo_corrections= {
    "f3mal3": "female",
    "mal3": "male",

    "m3rsin": "mersin",
    "gaziant3p": "gaziantep",
    "kays3ri": "kayseri",
    "eskiş3hir":"eskişehir",

    "silv3r": "silver",
    "gu3st": "guest",
    "bronz3": "bronze",

    "mobil3": "mobile",
    "d3sktop": "desktop",
    "tabl3t": "tablet",

    "paid s3arch": "paid search",
    "r3f3rral": "referral",

    "d3bit card": "debit card",
    "cr3dit card": "credit card",
    "bank transf3r": "bank transf3r",
    "digital wall3t":"digital wallet",
    "cash on d3liv3ry": "cash on delivery",
    "bank transf3r": "bank transfer",

    "books & station3ry": "books & stationery",
    "groc3ri3s": "groceries",
    "hom3 & kitch3n": "home & kitchen",
    "b3auty": "beauty",
    "el3ctronics": "electronics"
}
df = df.replace(typo_corrections)

#we check whether we achieve our aim or not using .unique() function
print("\nNew values: ")
for col in defCols:
    print(f"\n--- {col} ---")
    print(df[col].unique()) #now we have unique values as we can see

for col in defCols: 
    print()
    print(df[col].value_counts()) #we check the value counts here

--- gender ---
['male' 'f3mal3' 'female' 'nan' 'mal3']

--- city ---
['kayseri' 'bursa' 'i̇stanbul' 'adana' 'antalya' 'ankara' 'trabzon'
 'mersin' 'konya' 'gaziantep' 'i̇zmir' 'eskişehir' 'm3rsin' 'gaziant3p'
 'kays3ri' 'nan' 'eskiş3hir']

--- membership_tier ---
['bronze' 'gold' 'silver' 'silv3r' 'nan' 'guest' 'gu3st' 'bronz3']

--- device_type ---
['desktop' 'mobile' 'mobil3' 'tablet' 'nan' 'd3sktop' 'tabl3t']

--- traffic_source ---
['organic' 'social' 'email' 'paid s3arch' 'paid search' 'referral' 'nan'
 'r3f3rral']

--- payment_method ---
['cr3dit card' 'credit card' 'debit card' 'digital wallet'
 'cash on delivery' 'bank transfer' 'd3bit card' 'bank transf3r'
 'digital wall3t' 'nan' 'cash on d3liv3ry']

--- product_category ---
['fashion' 'electronics' 'groceries' 'sports' 'home & kitchen'
 'books & station3ry' 'beauty' 'groc3ri3s' 'hom3 & kitch3n' 'b3auty'
 'books & stationery' 'el3ctronics' 'nan']

New values:

--- gender ---
['male' 'female' 'nan']

--- city ---
['kayseri' 'bursa' 'i̇stanbul' 'adana' 'antalya' 'ankara' 'trabzon'
 'mersin' 'konya' 'gaziantep' 'i̇zmir' 'eskişehir' 'nan']

--- membership_tier ---
['bronze' 'gold' 'silver' 'nan' 'guest']

--- device_type ---
['desktop' 'mobile' 'tablet' 'nan']

--- traffic_source ---
['organic' 'social' 'email' 'paid search' 'referral' 'nan']

--- payment_method ---
['credit card' 'debit card' 'digital wallet' 'cash on delivery'
 'bank transfer' 'nan']

--- product_category ---
['fashion' 'electronics' 'groceries' 'sports' 'home & kitchen'
 'books & stationery' 'beauty' 'nan']

gender
male      887
female    823
nan        15
Name: count, dtype: int64

city
i̇stanbul    533
ankara       232
i̇zmir       163
bursa        143
antalya      130
konya        101
kayseri       86
adana         84
mersin        84
gaziantep     74
eskişehir     40
trabzon       37
nan           18
Name: count, dtype: int64

membership_tier
bronze    597
guest     515
silver    420
gold      171
nan        22
Name: count, dtype: int64

device_type
mobile     1237
desktop     389
tablet       84
nan          15
Name: count, dtype: int64

traffic_source
organic        695
paid search    428
social         318
email          168
referral        96
nan             20
Name: count, dtype: int64

payment_method
credit card         1022
cash on delivery     251
debit card           176
digital wallet       159
bank transfer         99
nan                   18
Name: count, dtype: int64

product_category
fashion               399
electronics           326
home & kitchen        319
groceries             192
sports                166
beauty                166
books & stationery    138
nan                    19
Name: count, dtype: int64

In [11]:
# --- COMBINING A DATE COLUMN  --- (Step 11)
#since we do not have month and day values (we only have year), we cannot create a date column.

In [12]:
# --- FIXING DATA TYPES  --- (Step 12)

#checking the data types before the change
print(df.dtypes)

#changing the data types accordingly
df["year"] = df["year"].astype("Int64")
df["gender"] = df["gender"].astype(object)
df["age"] = df["age"].astype("Int64")
df["city"] = df["city"].astype(object)
df["membership_tier"] = df["membership_tier"].astype(object)
df["device_type"] = df["device_type"].astype(object)
df["traffic_source"] = df["traffic_source"].astype(object)
df["payment_method"] = df["payment_method"].astype(object)
df["product_category"] = df["product_category"].astype(object)
df["items_in_cart"] = df["items_in_cart"].astype("Int64")
df["basket_value_try"] = df["basket_value_try"].astype("float64")
df["discount_rate"] = df["discount_rate"].astype("float64")
df["delivery_days"] = df["delivery_days"].astype("float64")
df["satisfaction_score"] = df["satisfaction_score"].astype("float64")
df["repeat_purchase_90d"] = df["repeat_purchase_90d"].astype(bool)

#verifying the outputs
print()
print(df.dtypes)

year                   float64
gender                  object
age                    float64
city                    object
membership_tier         object
device_type             object
traffic_source          object
payment_method          object
product_category        object
items_in_cart          float64
basket_value_try       float64
discount_rate           object
delivery_days          float64
satisfaction_score     float64
repeat_purchase_90d    float64
dtype: object

year                     Int64
gender                  object
age                      Int64
city                    object
membership_tier         object
device_type             object
traffic_source          object
payment_method          object
product_category        object
items_in_cart            Int64
basket_value_try       float64
discount_rate          float64
delivery_days          float64
satisfaction_score     float64
repeat_purchase_90d       bool
dtype: object

In [13]:
# --- DESCRIPTIVE STATISTICS --- (Step 13)
# using .describe() to access statistics of the data
stats = df.describe().T
print(stats)

#from the table we can say that there are missing values which will be handled in step 16. Other than NaN values, there are no unusual behaviors.

                     count        mean         std     min     25%     50%  \
year                1712.0  2021.33236     1.95147  2018.0  2020.0  2021.0
age                 1708.0   32.261124    9.645368    18.0    25.0    32.0
items_in_cart       1707.0    2.466901    1.641147     1.0     1.0     2.0
basket_value_try    1713.0  665.705114  782.916528   34.86  231.52  434.02
discount_rate       1708.0    0.134336    0.069855     0.0   0.084   0.134
delivery_days       1714.0    2.735123     0.92691     1.0     2.0     3.0
satisfaction_score  1713.0     4.01763    0.568213     2.3     3.6     4.0

                       75%       max
year                2023.0    2024.0
age                   39.0      69.0
items_in_cart          3.0      11.0
basket_value_try    806.84  10552.29
discount_rate        0.181     0.356
delivery_days          3.0       6.0
satisfaction_score     4.4       5.0

In [14]:
# --- DETECTING OUTLIERS --- (Step 14)

#defining the columns we want to search outliers
cols = df.select_dtypes(include=["Int64","float64"]).columns.drop("year")
for col in cols:
    q1, q3 = df[col].quantile([0.25, 0.75])
    iqr = q3 - q1 

    outliers = (df[col] < q1 - 1.5*iqr) | (df[col] > q3 + 1.5*iqr) #defining outliers
    num_outliers = outliers.sum()

    if num_outliers > 0: #if we detect outliers
        mean_val = df[col].mean()

        if str(df[col].dtype) == "Int64": #if the type is int64 then we will also change the mean value to prevent errors
            mean_val = int(mean_val)
        else:
            mean_val = round(mean_val, 2) #we will round floats up to 2 decimals
        df.loc[outliers, col] = mean_val
        print(f"{col}: found {num_outliers} outliers and changed them with mean value ({mean_val}).")
    else:
        print(f"{col}: No outliers detected.")

age: found 8 outliers and changed them with mean value (32).
items_in_cart: found 48 outliers and changed them with mean value (2).
basket_value_try: found 118 outliers and changed them with mean value (665.71).
discount_rate: found 4 outliers and changed them with mean value (0.13).
delivery_days: found 44 outliers and changed them with mean value (2.74).
satisfaction_score: found 6 outliers and changed them with mean value (4.02).

In [ ]:
# --- CHECKING UNIFORMITY --- (Step 15)

#for categorical ones we can check if the values are unique
cat_cols = df.select_dtypes(include="object").columns
for col in cat_cols:
    print(f"\nColumn: {col}")
    print(f"Unique Values ({len(df[col].unique())}):")
    print(df[col].unique()) 

#for numerical values we can check min and max values of each column
num_cols = df.select_dtypes(include=['number']).columns.drop('year', errors='ignore')

for col in num_cols:
    print(f"\nColumn: {col}")
    print(f"Min: {df[col].min()}  |  Max: {df[col].max()}") #if all values are within the domain of each column, then we achieve uniformity

Column: gender
Unique Values (3):
['male' 'female' 'nan']

Column: city
Unique Values (13):
['kayseri' 'bursa' 'i̇stanbul' 'adana' 'antalya' 'ankara' 'trabzon'
 'mersin' 'konya' 'gaziantep' 'i̇zmir' 'eskişehir' 'nan']

Column: membership_tier
Unique Values (5):
['bronze' 'gold' 'silver' 'nan' 'guest']

Column: device_type
Unique Values (4):
['desktop' 'mobile' 'tablet' 'nan']

Column: traffic_source
Unique Values (6):
['organic' 'social' 'email' 'paid search' 'referral' 'nan']

Column: payment_method
Unique Values (6):
['credit card' 'debit card' 'digital wallet' 'cash on delivery'
 'bank transfer' 'nan']

Column: product_category
Unique Values (8):
['fashion' 'electronics' 'groceries' 'sports' 'home & kitchen'
 'books & stationery' 'beauty' 'nan']

Column: age
Min: 18  |  Max: 60

Column: items_in_cart
Min: 1  |  Max: 6

Column: basket_value_try
Min: 34.86  |  Max: 1666.17

Column: discount_rate
Min: 0.0  |  Max: 0.326

Column: delivery_days
Min: 1.0  |  Max: 4.0

Column: satisfaction_score
Min: 2.4  |  Max: 5.0

In [ ]:
# --- DETECTING NAN VALUES AND REPLACING THEM (IMPUTATION) --- (Step 16)

# replacing all string/nan/NA values with standardized numpy NaN --> this was the most important step I think
df = df.replace(["NA", "na", "N/A", "", "nan"], np.nan)

nNaN = df.isnull().sum()
NaNRatio = (nNaN / len(df)) * 100

print("Missing Value Ratios (%):")
print(NaNRatio[NaNRatio > 0].round(2)) #show only columns with missing values

# imputation part is here
for col in df.columns:
    if df[col].isnull().sum() > 0: # dealing with only columns with NaN values
        
        # if the column is a string value, we fill with the mode value
        if df[col].dtype == "object" or df[col].dtype.name == "category":
            mode_val = df[col].mode()[0]
            df[col] = df[col].fillna(mode_val)
            print(f"{col:<20} -> Filled with MODE: '{mode_val}'")
            
        #if the column is a numerical one, we fill with the mean value
        else:
            mean_val = df[col].mean()
            if "int" in str(df[col].dtype).lower():
                fill_val = int(mean_val) #if it's an integer fill it with mean
            else:
                fill_val = round(mean_val, 2) #round to 2 decimals if it is a float
            
            df[col] = df[col].fillna(fill_val)
            print(f"{col:<20} -> Filled with mean: {fill_val}")

print("\n")
print("FINAL CHECK: Total Remaining NaN Values:", df.isnull().sum().sum())

Missing Value Ratios (%):
year                  0.75
gender                0.87
age                   0.99
city                  1.04
membership_tier       1.28
device_type           0.87
traffic_source        1.16
payment_method        1.04
product_category      1.10
items_in_cart         1.04
basket_value_try      0.70
discount_rate         0.99
delivery_days         0.64
satisfaction_score    0.70
dtype: float64
year                 -> Filled with mean: 2021
gender               -> Filled with MODE: 'male'
age                  -> Filled with mean: 32
city                 -> Filled with MODE: 'i̇stanbul'
membership_tier      -> Filled with MODE: 'bronze'
device_type          -> Filled with MODE: 'mobile'
traffic_source       -> Filled with MODE: 'organic'
payment_method       -> Filled with MODE: 'credit card'
product_category     -> Filled with MODE: 'fashion'
items_in_cart        -> Filled with mean: 2
basket_value_try     -> Filled with mean: 513.64
discount_rate        -> Filled with mean: 0.13
delivery_days        -> Filled with mean: 2.68
satisfaction_score   -> Filled with mean: 4.02


FINAL CHECK: Total Remaining NaN Values: 0

In [17]:
# Final Step
# We want to save our file as a new file.
df.to_csv("cleaned_ecommerce_data.csv", index=False)